name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd browser-tests
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
        browserstack_user: ${{ secrets.browserstack_user }}
        browserstack_key: ${{ secrets.browserstack_key }}
